[정수론] 3월 5일
Altu-Bitu-6/Altu-Bitu-YoonJiwoon pull request #3
Opened 2024-03-05 09:42 UTC by Jiwoon-Yoon

### 인적사항
학번 : 2276209
이름 : 윤지운
</br>

### 과제제출
기존 제출: 1735, 2840, 6588
추가 제출:
</br>

2024-03-08 07:02 UTC, chae-jpg approved these changes
**[정수론 이론 코드리뷰 완료]**

1735(P3), 6588(P1)
지운님 안녕하세요! 코드 리뷰 완료되었습니다👍
현재 6588번 문제에서 백준 상으로 시간 초과 판정이 나오고 있습니다 😢 
리뷰 확인해보시고 수정하신 뒤 리뷰어 호출 부탁드립니다!
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-03-08 07:02 UTC, chae-jpg commented on 03_정수론/필수/1735.cpp
> +int gcdIter(int a, int b) {
유클리드 호제법을 잘 구현해주셨어요!

2024-03-08 07:02 UTC, chae-jpg commented on 03_정수론/필수/1735.cpp
> +	ans1 = b * c + a * d;
연산 후 분자와 분모를 각각 잘 구해주셨네요!

2024-03-08 07:02 UTC, chae-jpg commented on 03_정수론/필수/1735.cpp
> +	ans1 /= gcd;
기약분수가 되기 위한 조건을 이용해서 새로운 분자와 분모를 잘 찾아주셨네요!

2024-03-08 07:02 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +const int MAX_SIZE = 100000;
P1
자주 사용하는 큰 수의 상수 표현 너무 좋아요!
다만 이 부분에서 사소한 실수로 인해서 현재 오답판정이 나오고 있습니다 😢 
문제 조건을 다시 확인해보세요!

2024-03-08 07:02 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +void isPrime(vector<bool>& v) {
에라토스테네스의 체를 이용해서 소수를 잘 판정해주셨네요!

2024-03-08 07:02 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +void prove(int n, vector<bool>& v) {
함수 분리 좋아요!

2024-03-08 07:02 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +		}
합이 두 소수로 이루어진 경우를 구해둔 소수 여부 배열을 이용해서 잘 찾아주셨어요!

2024-03-08 07:02 UTC, chae-jpg commented on 03_정수론/필수/6588.cpp
> +			cout << n << " = " << i << " + " << n-i << "\n";  //결과 출력
P3
알튜비튜에서는 입출력은 메인 함수에서만 하도록 권장하고 있습니다!
string을 메인에 리턴하고, 그 결과를 메인에서 출력하는 식으로 변경하면 더 좋을 것 같아요~

2024-03-08 07:35 UTC, kimhj010502 reviewed
**[정수론 구현 문제 코드 리뷰 완료]**

2840(P2)

지운님 안녕하세요!
과제하시느라 수고 많으셨습니다!! 어려운 문제인데도 잘 풀어주셨네요! 🥰 
코드에 대한 주석도 너무 좋았습니다 👍
몇 가지 사소한 코멘트 드렸습니다.
궁금한 점이 있으면 리뷰어를 호출해주세요!

2024-03-08 07:35 UTC, kimhj010502 commented on 03_정수론/필수/2840.cpp
> +int main() {
P2. 모든 연산을 main 함수에서 해주었네요~ 알튜비튜에서는 함수로 구현할 수 있는 부분은 최대한 함수를 따로 정의해서 사용하는 것을 권장하고 있어요!

2024-03-08 07:35 UTC, kimhj010502 commented on 03_정수론/필수/2840.cpp
> +		v[pos % n] = c;
18번째 줄에서 `pos = (pos + s) % n;`으로 증감해준 다음 아래는 다 pos로 작성해주는 게 더 깔끔할 것 같아요!

2024-03-08 07:35 UTC, kimhj010502 commented on 03_정수론/필수/2840.cpp
> +		}
하나씩 확인하면서 알파벳의 중복을 체크해주셨네요~ 이 방법도 좋지만 circle의 크기가 커지면 시간 초과가 발생할 수 있으니 알파벳의 중복을 체크하는 vector를 만들어서 관리하는 샘플 답안 코드를 참고해주세요!

2024-03-08 07:35 UTC, kimhj010502 commented on 03_정수론/필수/2840.cpp
> +	}
연산 과정을 잘 구현해주셨는데 두 개의 반복문이 아닌 한 개의 반복문으로 작성하는 방법도 고려해주세요!

2024-03-10 13:40 UTC, chae-jpg requested changes
안녕하세요 지운님! 코드에서 수정 필요한 부분이 있어 다시 코멘트 드립니다 😢
리뷰 확인 후 수정하신 뒤, 다시 리뷰어를 호출해주세요!

2024-03-13 02:43 UTC, chae-jpg approved these changes
**[정수론 이론 코드리뷰 완료]**

안녕하세요 지운님! 코드 수정 확인되었습니다. 수고하셨습니다~!

2024-03-16 13:26 UTC, merged